name: pypbee
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12,<3.13
  - pip
  - numpy>=1.26
  - scipy<=1.15.3
  - matplotlib>=3.8.2
  - pathos>=0.3.4
  - xlrd>=2.0.1
  - openpyxl>=3.1.5
  - pyqt>=5.15,<5.16
  - pip:
      - pygmm>=0.7.1
      - pydoe3>=1.0.4
      - eqsig>=1.2.17
      - python-benedict>=0.35.0
      - openseespy
